### ISSUE TITLE
Issue!!

### ISSUE THREAD

**Issue by cianoner** [raghavkhanna30/instagram-bot#1]
Hey! seem to be having an issue with importing 

PS C:\Users\oweng\Desktop\instagram-bot-master> & C:/Users/oweng/AppData/Local/Programs/Python/Python38-32/python.exe c:/Users/oweng/Desktop/instagram-bot-master/bot.py 
Traceback (most recent call last):
  File "c:/Users/oweng/Desktop/instagram-bot-master/bot.py", line 1, in <module>
    from instapy import InstaPy
  File "C:\Users\oweng\AppData\Local\Programs\Python\Python38-32\lib\instapy\__init__.py", line 6, in <module>
    from .instapy import InstaPy
  File "C:\Users\oweng\AppData\Local\Programs\Python\Python38-32\lib\instapy\instapy.py", line 21, in <module>
    from .clarifai_util import check_image
  File "C:\Users\oweng\AppData\Local\Programs\Python\Python38-32\lib\instapy\clarifai_util.py", line 3, in <module>
    from clarifai.rest import ClarifaiApp
  File "C:\Users\oweng\AppData\Local\Programs\Python\Python38-32\lib\clarifai\rest\__init__.py", line 3, in <module>
  File "C:\Users\oweng\AppData\Local\Programs\Python\Python38-32\lib\clarifai\rest\client.py", line 36, in <module>
    from clarifai.rest.grpc.proto.clarifai.api.endpoint_pb2_grpc import V2Stub
  File "C:\Users\oweng\AppData\Local\Programs\Python\Python38-32\lib\clarifai\rest\grpc\proto\clarifai\api\endpoint_pb2_grpc.py", line 2, in <module>
    import grpc
  File "C:\Users\oweng\AppData\Local\Programs\Python\Python38-32\lib\grpc\__init__.py", line 23, in <module>
    from grpc._cython import cygrpc as _cygrpc
ImportError: cannot import name 'cygrpc' from 'grpc._cython' (C:\Users\oweng\AppData\Local\Programs\Python\Python38-32\lib\grpc\_cython\__init__.py)
PS C:\Users\oweng\Desktop\instagram-bot-master> & C:/Users/oweng/AppData/Local/Programs/Python/Python38-32/python.exe c:/Users/oweng/Desktop/instagram-bot-master/bot.py 
Traceback (most recent call last):
  File "c:/Users/oweng/Desktop/instagram-bot-master/bot.py", line 1, in <module>
    from instapy import InstaPy
  File "C:\Users\oweng\AppData\Local\Programs\Python\Python38-32\lib\instapy\__init__.py", line 6, in <module>
    from .instapy import InstaPy
  File "C:\Users\oweng\AppData\Local\Programs\Python\Python38-32\lib\instapy\instapy.py", line 21, in <module>
    from .clarifai_util import check_image
  File "C:\Users\oweng\AppData\Local\Programs\Python\Python38-32\lib\instapy\clarifai_util.py", line 3, in <module>
    from clarifai.rest import ClarifaiApp
  File "C:\Users\oweng\AppData\Local\Programs\Python\Python38-32\lib\clarifai\rest\__init__.py", line 3, in <module>
    from clarifai.rest.client import ApiClient
  File "C:\Users\oweng\AppData\Local\Programs\Python\Python38-32\lib\clarifai\rest\client.py", line 36, in <module>
    from clarifai.rest.grpc.proto.clarifai.api.endpoint_pb2_grpc import V2Stub
  File "C:\Users\oweng\AppData\Local\Programs\Python\Python38-32\lib\clarifai\rest\grpc\proto\clarifai\api\endpoint_pb2_grpc.py", line 2, in <module>
    import grpc
  File "C:\Users\oweng\AppData\Local\Programs\Python\Python38-32\lib\grpc\__init__.py", line 23, in <module>
    from grpc._cython import cygrpc as _cygrpc
ImportError: cannot import name 'cygrpc' from 'grpc._cython' (C:\Users\oweng\AppData\Local\Programs\Python\Python38-32\lib\grpc\_cython\__init__.py)
PS C:\Users\oweng\Desktop\instagram-bot-master>

**Comment by raghavkhanna30** [comment]
Hi! Did you install the requirements.txt? 
Try doing-
Run pip install -r requirements.txt (Python 2), 
or pip3 install -r requirements.txt (Python 3).

Hope it helps!
